const { createClient } = require('@supabase/supabase-js');
require('dotenv').config({ path: '.env.local' });

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error("Missing Supabase environment variables.");
    process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

const rawData = [
    {
        status: "Done",
        nama: "Ziarah anak arwah Jhanat",
        mula: "16 Jan 2026",
        tamat: "",
        masaM: "2:00 pm",
        masaT: "8:30 pm",
        tempat: "Hospital Al-Sultan Abdullah, UiTM Puncak Alam, Selangor",
        kawasan: [],
        jenis: ["Ziarah Mualaf"],
        kat: "Mualaf",
        sub: ["Mualaf"],
        rh: 1, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 3, total: 4,
        anjuran: ["Staf Negeri", "RH"],
        ikram: "",
        fb: "https://www.facebook.com/share/p/17EWmBdroz/?mibextid=wwXIfr",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "𝐊𝐚𝐫𝐧𝐢𝐯𝐚𝐥 𝐌𝐚𝐬𝐣𝐢𝐝 𝐉𝐚𝐦𝐞𝐤 𝐂𝐢𝐧𝐚 𝐌𝐮𝐬𝐥𝐢𝐦 𝐊𝐥𝐚𝐧𝐠",
        mula: "3 Jan 2026",
        tamat: "",
        masaM: "9:00 am",
        masaT: "4:00 pm",
        tempat: "Masjid Jamek Cina Muslim, Klang",
        kawasan: [],
        jenis: ["Masjid Open Day / Masjid Tour"],
        kat: "Outreach",
        sub: [],
        rh: 6, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 0, total: 6,
        anjuran: [],
        ikram: "",
        fb: "https://www.facebook.com/share/p/1CEGwNJkKM/",
        c1: "", c2: "", selesai: false
    },
    {
        status: "Done",
        nama: "𝐏𝐫𝐨𝐠𝐫𝐚𝐦 𝐌𝐨𝐭𝐢𝐯𝐚𝐬𝐢 & 𝐁𝐚𝐜𝐤 𝐭𝐨 𝐒𝐜𝐡𝐨𝐨𝐥",
        mula: "4 Jan 2026",
        tamat: "",
        masaM: "2:30 pm",
        masaT: "4:30 pm",
        tempat: "Pejabat Ikram Kuala Selangor",
        kawasan: ["Kuala Selangor"],
        jenis: ["Back To School"],
        kat: "Mualaf",
        sub: ["Mualaf"],
        rh: 15, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 14, total: 29,
        anjuran: ["RH", "IKRAM"],
        ikram: "Kuala Selangor",
        fb: "https://www.facebook.com/share/p/1FAq775Wcp/",
        c1: "", c2: "", selesai: false
    },
    {
        status: "Done",
        nama: "Retreat Staff Selagor",
        mula: "13 Feb 2026",
        tamat: "",
        masaM: "8:30 am",
        masaT: "5:30 pm",
        tempat: "Pejabat HCF Selangor",
        kawasan: [],
        jenis: [],
        kat: "Pengurusan",
        sub: ["Pengurusan"],
        rh: 9, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 0, total: 9,
        anjuran: ["Staf Negeri", "HQ"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: false
    },
    {
        status: "Done",
        nama: "Gathering RH Kuala Selangor",
        mula: "25 Jan 2026",
        tamat: "",
        masaM: "3:00 pm",
        masaT: "5:00 pm",
        tempat: "Pejabat Ikram Kuala Selangor",
        kawasan: ["Kuala Selangor"],
        jenis: ["RH Gathering"],
        kat: "RH",
        sub: ["RH"],
        rh: 18, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 0, total: 18,
        anjuran: ["RH"],
        ikram: "Kuala Selangor",
        fb: "https://www.facebook.com/share/p/1AZoestM2s/",
        c1: "", c2: "", selesai: false
    },
    {
        status: "Done",
        nama: "5X GROWTH SOLAH",
        mula: "17 Jan 2026",
        tamat: "",
        masaM: "7:30 am",
        masaT: "1:00 pm",
        tempat: "Masjid Bandar Saujana Putra, Jenjarom",
        kawasan: [],
        jenis: ["Kursus Pemantapan Aqidah & Ibadah Mualaf"],
        kat: "Mualaf",
        sub: [],
        rh: 2, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 0, total: 2,
        anjuran: ["Staf Negeri", "HQ", "Lain-lain"],
        ikram: "",
        fb: "https://www.facebook.com/share/p/1DjHhxuZ5Z/",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Cancelled",
        nama: "Pindah Office Selangor",
        mula: "5 Jan 2026",
        tamat: "",
        masaM: "9:00 am",
        masaT: "5:30 pm",
        tempat: "Pejabat HCF Selangor SS19",
        kawasan: [],
        jenis: [],
        kat: "",
        sub: [],
        rh: 0, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 0, total: 0,
        anjuran: [],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: false
    },
    {
        status: "Done",
        nama: "Majlis pengislaman nancy",
        mula: "5 Jan 2026",
        tamat: "",
        masaM: "9:00 am",
        masaT: "5:30 pm",
        tempat: "Pejabat HCF Selangor SS19",
        kawasan: [],
        jenis: [],
        kat: "Outreach",
        sub: [],
        rh: 3, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 4,
        anjuran: [],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman Jannah Lee",
        mula: "26 Jan 2026",
        tamat: "",
        masaM: "11:00 am",
        masaT: "13:30:00",
        tempat: "Pejabat HCF Selangor SS20",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach", "Mualaf", "Dana / Korporat", "Kesedaran Dakwah", "Kesedaran Mualaf"],
        rh: 4, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 11,
        anjuran: ["Staf Negeri"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman Juna",
        mula: "30 Jan 2026",
        tamat: "",
        masaM: "10:00 am",
        masaT: "11:00 am",
        tempat: "Pejabat HCF Selangor SS21",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 4, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 6,
        anjuran: ["Staf Negeri"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Ziarah anak arwah Jhanat ",
        mula: "17 Jan 2026",
        tamat: "",
        masaM: "8:00 pm",
        masaT: "10:30 am",
        tempat: "Seksyen 25 Seri Muda Shah Alam",
        kawasan: ["Shah Alam"],
        jenis: ["Ziarah Mualaf"],
        kat: "Mualaf",
        sub: ["Mualaf"],
        rh: 2, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 3, total: 4,
        anjuran: ["Staf Negeri"],
        ikram: "",
        fb: "https://www.facebook.com/share/p/1MiJxx1Rwe/",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Ceramah Kesedaran Dakwah",
        mula: "30 Jan 2026",
        tamat: "",
        masaM: "12:30 pm",
        masaT: "1:30 pm",
        tempat: "Masjid Abu Bakar As-Siddiq SS19/6 Subang",
        kawasan: [],
        jenis: ["Hidayah Talk /Ceramah Kesedaran Dakwah & Bimbingan Mualaf"],
        kat: "Kesedaran Dakwah",
        sub: ["Kesedaran Dakwah"],
        rh: 3, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 0, total: 300,
        anjuran: ["Staf Negeri", "Lain-lain"],
        ikram: "",
        fb: "https://www.facebook.com/share/p/1Dc6eWHUaJ/",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman Fatimah & Zaharah",
        mula: "30 Jan 2026",
        tamat: "",
        masaM: "11:00 am",
        masaT: "12:30 pm",
        tempat: "Pejabat HCF Taman Melawati",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 2, daie: 0, nm: 2, qe: 0, madu: 0, sy: 2, mu: 0, total: 4,
        anjuran: ["Staf Negeri", "HQ"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Program ESQ Mualaf",
        mula: "24 Jan 2026",
        tamat: "25 Jan 2026",
        masaM: "8:30 am",
        masaT: "8:00 pm",
        tempat: "AEON Hall Seksyen  13",
        kawasan: ["Shah Alam"],
        jenis: ["Kursus Pemantapan Aqidah & Ibadah Mualaf"],
        kat: "Mualaf",
        sub: ["Mualaf"],
        rh: 1, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 9, total: 10,
        anjuran: ["Staf Negeri", "RH", "Lain-lain"],
        ikram: "",
        fb: "https://www.facebook.com/share/p/1SyPd4dwSn/",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Bengkel ASARA-PK",
        mula: "29 Jan 2026",
        tamat: "",
        masaM: "8:30 pm",
        masaT: "22:00:00",
        tempat: "Pejabat IKRAM Shah Alam",
        kawasan: ["Shah Alam"],
        jenis: ["Bengkel ASARA-PK"],
        kat: "Latihan Daie",
        sub: ["Latihan Daie"],
        rh: 26, daie: 0, nm: 0, qe: 0, madu: 0, sy: 0, mu: 0, total: 26,
        anjuran: ["IKRAM"],
        ikram: "Shah Alam",
        fb: "https://www.facebook.com/share/p/1L2AKEuhgc/",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman Daeren",
        mula: "31 Jan 2026",
        tamat: "",
        masaM: "10:30 am",
        masaT: "12:00 pm",
        tempat: "Pejabat HCF Taman Melawati",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 2, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 6,
        anjuran: ["Staf Negeri"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Mosque Tour Mingguan",
        mula: "25 Jan 2026",
        tamat: "",
        masaM: "9:30 am",
        masaT: "11:00 am",
        tempat: "Masjid Kota Kemuning",
        kawasan: ["Shah Alam"],
        jenis: ["Masjid Open Day / Masjid Tour"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 3, daie: 0, nm: 3, qe: 3, madu: 0, sy: 0, mu: 0, total: 6,
        anjuran: ["RH"],
        ikram: "",
        fb: "https://www.facebook.com/share/p/1HButixgrW/",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman VERRENIKANEKCI",
        mula: "5 Jan 2026",
        tamat: "",
        masaM: "10:00 am",
        masaT: "",
        tempat: "Pejabat HCF Selangor",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 3, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 4,
        anjuran: ["Staf Negeri", "RH"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman IRSYAD ZAHRAN",
        mula: "7 Jan 2026",
        tamat: "",
        masaM: "12:00 pm",
        masaT: "",
        tempat: "Pejabat HCF Selangor",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 3, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 4,
        anjuran: ["Staf Negeri"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Masjid Pengislaman ISKANDAR ZULKARNAIN JACOB",
        mula: "2 Jan 2026",
        tamat: "",
        masaM: "",
        masaT: "",
        tempat: "Pejabat HCF Melawati",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 3, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 4,
        anjuran: ["Staf Negeri", "HQ", "Lain-lain"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman SIVA",
        mula: "1 Jan 2026",
        tamat: "",
        masaM: "7:30 pm",
        masaT: "",
        tempat: "RESTORAN AROMA HIJRAH TTDI JAYA",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 4, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 5,
        anjuran: ["Staf Negeri", "RH"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman MYSHA INSYIRAH",
        mula: "1 Jan 2026",
        tamat: "",
        masaM: "",
        masaT: "",
        tempat: "Pejabat HCF Selangor",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 4, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 5,
        anjuran: ["Staf Negeri", "RH", "Lain-lain"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman NUR IMAN LIVIANA",
        mula: "9 Jan 2026",
        tamat: "",
        masaM: "3:30 pm",
        masaT: "",
        tempat: "Pejabat HCF Selangor",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 3, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 4,
        anjuran: ["Staf Negeri", "HQ"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman HARVINTH SHAN BIN SUMMUGAM",
        mula: "15 Feb 2026",
        tamat: "",
        masaM: "3:00 pm",
        masaT: "",
        tempat: "Pejabat HCF HQ",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 3, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 4,
        anjuran: ["HQ"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    },
    {
        status: "Done",
        nama: "Majlis Pengislaman AAMIRA CLARITO",
        mula: "23 Feb 2026",
        tamat: "",
        masaM: "12:30 pm",
        masaT: "",
        tempat: "Pejabat HCF HQ",
        kawasan: [],
        jenis: ["Majlis Pengislaman"],
        kat: "Outreach",
        sub: ["Outreach"],
        rh: 3, daie: 0, nm: 1, qe: 0, madu: 0, sy: 1, mu: 0, total: 4,
        anjuran: ["Staf Negeri"],
        ikram: "",
        fb: "",
        c1: "", c2: "", selesai: true
    }
];

function parseDate(str) {
    if (!str) return null;
    const months = {
        'Jan': '01', 'Feb': '02', 'Mar': '03', 'Apr': '04', 'May': '05', 'Jun': '06',
        'Jul': '07', 'Aug': '08', 'Sep': '09', 'Oct': '10', 'Nov': '11', 'Dec': '12'
    };
    const parts = str.split(' ');
    if (parts.length === 3) {
        const d = parts[0].padStart(2, '0');
        const m = months[parts[1]] || '01';
        const y = parts[2];
        return `${y}-${m}-${d}`;
    }
    return str;
}

const formattedData = rawData.map(item => {
    const startDate = parseDate(item.mula);
    const dateObj = new Date(startDate);

    return {
        negeri: "Selangor",
        tahun: dateObj.getFullYear(),
        bulan: dateObj.getMonth() + 1,
        status_program: item.status,
        nama_program: item.nama,
        tarikh_mula: startDate || null,
        tarikh_tamat: parseDate(item.tamat) || null,
        masa_mula: item.masaM || null,
        masa_tamat: item.masaT || null,
        tempat: item.tempat,
        kawasan_cawangan: item.kawasan,
        jenis_program: item.jenis,
        kategori_utama: item.kat,
        sub_kategori: item.sub,
        kehadiran_rh: item.rh || 0,
        kehadiran_daie: item.daie || 0,
        kehadiran_non_muslim: item.nm || 0,
        kehadiran_quality: item.qe || 0,
        kehadiran_madu: item.madu || 0,
        kehadiran_syahadah: item.sy || 0,
        kehadiran_muallaf: item.mu || 0,
        kehadiran_keseluruhan: item.total || 0,
        anjuran: item.anjuran,
        kawasan_ikram: item.ikram,
        link_facebook: item.fb,
        catatan_1: item.c1,
        catatan_2: item.c2,
        selesai_laporan: item.selesai
    };
});

async function run() {
    console.log(`Importing ${formattedData.length} programs...`);
    const { data, error } = await supabase.from('programs').insert(formattedData);
    if (error) {
        console.error("Error importing data:", error);
    } else {
        console.log("Successfully imported data!");
    }
}

run();
